
services:

  db:
    image: mysql:8.0
    container_name: sep_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db/sep_productos.sql:/docker-entrypoint-initdb.d/sep_productos.sql:ro
    ports:
      - "3307:3306"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: sep_productos
      DB_USER: sep_user
      DB_PASSWORD: sep_password
    volumes:
      - ./app:/app

volumes:
  db_data:
